name: x_config_gen
description: A tool for generating Xray and sing-box configs.
version: 0.1.3
repository: https://github.com/DHR60/x_config_gen

environment:
  sdk: '^3.8.0'

# Add regular dependencies here.
dependencies:
  freezed_annotation: ^3.1.0
  json_annotation: ^4.10.0

dev_dependencies:
  lints: ^6.1.0
  test: ^1.29.0
  build_runner: ^2.10.5
  freezed: ^3.2.4
  json_serializable: ^6.12.0
